scripts: dtc: libfdt: Add missing define to contine building
Fix this error:

../lib/../scripts/dtc/libfdt/fdt.c:48:18: error: use of undeclared identifier 'INT32_MAX'
        if (totalsize < INT32_MAX)
                        ^
1 error generated.